packages:
  - apps/*
  - packages/*
strictPeerDependencies: true
minimumReleaseAge: 1440
overrides:
  '@prisma/config>deepmerge-ts': 8.0.0
  'prisma>mysql2': 3.23.1
  '@nestjs/platform-express>multer': 2.3.0
allowBuilds:
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  msgpackr-extract: false
  protobufjs: false
